spring.application.name=jpamysql

spring.datasource.url=jdbc:mysql://localhost:3306/jpamysql
spring.datasource.username=spjain
spring.datasource.password=spjain

# Configure JPA/Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
## use the 'create' option to create the database schema on startup,
## or 'update' to update it without dropping existing data
## However set it to none, if you dont want to disturb your DB schema.
## Recommended way is to manage it using liquibase or flyway.
## This is just a demo application, for a class I am teaching.
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
